name: Build
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          sudo apt install capnproto libcapnp-dev ninja-build ccache
          pip install angr
      - name: Initialize compiler cache
        id: cache
        uses: actions/cache@v2
        with:
          path: /tmp/ccache
          key: cache-${{ github.sha }}
          restore-keys: cache-
      - name: Install
        run: |
          export CCACHE_DIR=/tmp/ccache
          export CCACHE_MAXSIZE=512M
          export PATH="/usr/lib/ccache:$PATH"
          git config --global user.name 'Tester'
          git config --global user.email 'nobody@nowhere'
          pip install --verbose .
          echo -e "\nCompiler Cache Stats:"
          ccache -s -c
      - name: Test
        run: |
          cd tests
          python -m unittest
